name: criticalneuro
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - r-base=4.4.3
  - r-arrow=16.1.0
  - r-essentials=4.4
  - bioconductor-wgcna
  - bioconductor-sva=3.52.0
  - bioconductor-fgsea=1.30.0
  - bioconductor-biotip
  - bioconductor-limma
  - r-lme4
  - r-lmertest
  - r-optparse
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-yaml
  - pip
  - pip:
    - -r requirements_python.txt
