# ============================================================
# Stage 6: Publication Figure Generation
# ============================================================
# Generates all publication-ready figures from pipeline outputs.
#
# Called by run_pipeline.py via subprocess
# Args: --config, --results_dir, --output

suppressPackageStartupMessages({
  library(yaml)
  library(optparse)
  library(ggplot2)
  library(dplyr)
})

# --- Parse arguments ---
option_list <- list(
  make_option("--config",      type = "character"),
  make_option("--results_dir", type = "character"),  # pipeline results directory
  make_option("--output",      type = "character")   # figures output directory
)
opt <- parse_args(OptionParser(option_list = option_list))
cfg <- yaml.load_file(opt$config)

results_dir <- opt$results_dir
figures_dir <- opt$output
dir.create(figures_dir, showWarnings = FALSE, recursive = TRUE)

cat(sprintf("[Figures] Results directory: %s\n", results_dir))
cat(sprintf("[Figures] Output directory: %s\n", figures_dir))

# --- Figure 1: BioTIP MCI scores by stage ---
mci_path <- file.path(results_dir, "biotip", "biotip_stage_mci_scores.csv")
if (file.exists(mci_path)) {
  mci_df <- read.csv(mci_path, stringsAsFactors = FALSE)

  if (cfg$analysis_mode == "longitudinal") {
    stage_order <- c("T3_baseline", "T2_early", "T1_preClinical", "T0_AD")
    stage_labels <- c("T-3\n(Baseline)", "T-2\n(Early)", "T-1\n(Pre-Clinical)", "T0\n(AD Dx)")
  } else {
    stage_order <- c("CN_amyloid_negative", "Stable_MCI", "CN_amyloid_positive", "MCI_to_Dementia")
    stage_labels <- c("CN A-", "Stable MCI", "CN A+", "MCI->Dem")
  }

  mci_df$Stage <- factor(mci_df$Stage, levels = stage_order)
  mci_df <- mci_df[!is.na(mci_df$Stage), ]

  p_mci <- ggplot(mci_df, aes(x = Stage, y = MCI, fill = Stage)) +
    geom_col(width = 0.7, show.legend = FALSE) +
    geom_text(aes(label = sprintf("n=%d", N)), vjust = -0.5, size = 3) +
    scale_x_discrete(labels = stage_labels) +
    scale_fill_brewer(palette = "RdYlBu", direction = -1) +
    labs(title = "Module Criticality Index (MCI) by Disease Stage",
         subtitle = "BioTIP tipping-point detection",
         x = "Disease Stage", y = "MCI Score") +
    theme_classic(base_size = 14)

  ggsave(file.path(figures_dir, "figure_01_biotip_mci.pdf"), p_mci, width = 8, height = 5)
  ggsave(file.path(figures_dir, "figure_01_biotip_mci.png"), p_mci, width = 8, height = 5, dpi = 300)
  cat("[Figures] Figure 1 (BioTIP MCI) saved\n")
} else {
  cat("[Figures] BioTIP MCI scores not found — skipping Figure 1\n")
}

# --- Figure 2: l-DNB individual trajectories ---
# Already generated by stage4_ldnb.R; just verify it exists
traj_path <- file.path(figures_dir, "ldnb_individual_trajectories.pdf")
if (file.exists(traj_path)) {
  cat("[Figures] Figure 2 (l-DNB trajectories) already exists\n")
} else {
  cat("[Figures] l-DNB trajectory figure not found — may need to run stage4_ldnb.R\n")
}

# --- Figure 3: Permutation null distribution ---
perm_path <- file.path(results_dir, "biotip", "biotip_permutation_null.csv")
summary_path <- file.path(results_dir, "biotip", "biotip_summary.csv")
if (file.exists(perm_path) && file.exists(summary_path)) {
  perm_df <- read.csv(perm_path)
  summary_df <- read.csv(summary_path)

  observed <- summary_df$observed_MCI[1]
  emp_p <- summary_df$empirical_p[1]

  p_perm <- ggplot(perm_df, aes(x = Ic_random)) +
    geom_histogram(bins = 50, fill = "grey70", color = "grey40") +
    geom_vline(xintercept = observed, color = "red", linewidth = 1.2, linetype = "dashed") +
    annotate("text", x = observed, y = Inf, label = sprintf("Observed MCI = %.3f\np = %.4f", observed, emp_p),
             hjust = -0.1, vjust = 2, color = "red", size = 4) +
    labs(title = "BioTIP Permutation Test",
         subtitle = sprintf("%d permutations", nrow(perm_df)),
         x = "Permuted MCI Score", y = "Count") +
    theme_classic(base_size = 14)

  ggsave(file.path(figures_dir, "figure_03_permutation_test.pdf"), p_perm, width = 7, height = 5)
  ggsave(file.path(figures_dir, "figure_03_permutation_test.png"), p_perm, width = 7, height = 5, dpi = 300)
  cat("[Figures] Figure 3 (permutation test) saved\n")
} else {
  cat("[Figures] Permutation data not found — skipping Figure 3\n")
}

# --- Figure 4: IDNB boxplot by stage ---
ldnb_path <- file.path(results_dir, "ldnb", "ldnb_individual_scores.csv")
if (file.exists(ldnb_path)) {
  ldnb_df <- read.csv(ldnb_path, stringsAsFactors = FALSE)

  if ("Stage" %in% colnames(ldnb_df) && "IDNB" %in% colnames(ldnb_df)) {
    if (cfg$analysis_mode == "longitudinal") {
      ldnb_df$Stage <- factor(ldnb_df$Stage,
                               levels = c("stable_CO", "T3_baseline", "T2_early",
                                           "T1_preClinical", "T0_AD"))
    }
    ldnb_plot <- ldnb_df[!is.na(ldnb_df$Stage) & ldnb_df$Stage != "stable_CO", ]

    p_box <- ggplot(ldnb_plot, aes(x = Stage, y = IDNB, fill = Stage)) +
      geom_boxplot(alpha = 0.7, outlier.shape = 21) +
      geom_jitter(width = 0.2, alpha = 0.5, size = 1.5) +
      scale_fill_brewer(palette = "RdYlBu", direction = -1) +
      labs(title = "Individual l-DNB Scores by Disease Stage",
           x = "Disease Stage", y = "IDNB Score") +
      theme_classic(base_size = 14) +
      theme(legend.position = "none")

    ggsave(file.path(figures_dir, "figure_04_idnb_boxplot.pdf"), p_box, width = 8, height = 5)
    ggsave(file.path(figures_dir, "figure_04_idnb_boxplot.png"), p_box, width = 8, height = 5, dpi = 300)
    cat("[Figures] Figure 4 (IDNB boxplot) saved\n")
  }
} else {
  cat("[Figures] l-DNB scores not found — skipping Figure 4\n")
}

cat("[Figures] Figure generation complete\n")
