"""ADNI data loading and preprocessing.

Entry point for all ADNI data. Loads ADNIMERGE clinical data, SomaScan
proteomics, and plasma biomarkers, then assigns conversion trajectory
labels and merges everything into a single analysis-ready DataFrame.
"""

import logging
import re
from pathlib import Path

import numpy as np
import pandas as pd

from src.preprocessing.somascan_qc import identify_seq_columns

logger = logging.getLogger(__name__)


def load_adnimerge(config: dict) -> pd.DataFrame:
    """Load ADNIMERGE.csv and standardize columns.

    Reads the ADNIMERGE CSV generated by R/adnimerge_extract.R, standardizes
    column names to uppercase, parses EXAMDATE as datetime, encodes APOE4
    as binary carrier (1/0), and encodes sex as binary female (1/0).

    Parameters
    ----------
    config : dict
        Configuration dictionary with paths.adnimerge_csv.

    Returns
    -------
    pd.DataFrame
        Standardized ADNIMERGE DataFrame.

    Raises
    ------
    FileNotFoundError
        If ADNIMERGE.csv is missing. Message instructs user to run
        R/adnimerge_extract.R first.
    """
    filepath = Path(config["paths"]["adnimerge_csv"])

    if not filepath.exists():
        raise FileNotFoundError(
            f"ADNIMERGE.csv not found at {filepath}. "
            "Run 'Rscript R/adnimerge_extract.R' first to generate it."
        )

    df = pd.read_csv(filepath, low_memory=False)
    logger.info("Loaded ADNIMERGE: %d rows, %d columns", len(df), len(df.columns))

    # Standardize column names to uppercase
    df.columns = df.columns.str.upper()

    # Parse EXAMDATE as datetime
    if "EXAMDATE" in df.columns:
        df["EXAMDATE"] = pd.to_datetime(df["EXAMDATE"], errors="coerce")

    # Encode APOE4 as binary carrier (>=1 allele -> 1, else 0)
    if "APOE4" in df.columns:
        df["APOE4"] = (df["APOE4"] >= 1).astype(int)
        logger.info(
            "APOE4 carriers: %d/%d (%.1f%%)",
            df["APOE4"].sum(),
            df["APOE4"].notna().sum(),
            df["APOE4"].mean() * 100,
        )

    # Encode sex as binary female (1/0)
    sex_col = None
    for candidate in ["PTGENDER", "SEX", "GENDER"]:
        if candidate in df.columns:
            sex_col = candidate
            break

    if sex_col:
        df["SEX"] = (
            df[sex_col]
            .astype(str)
            .str.lower()
            .map({"female": 1, "f": 1, "male": 0, "m": 0, "2": 1, "1": 0})
        )
        if sex_col != "SEX":
            df = df.drop(columns=[sex_col])

    # Standardize participant ID column
    if "RID" not in df.columns:
        for candidate in ["PTID", "SUBJECT_ID"]:
            if candidate in df.columns:
                df = df.rename(columns={candidate: "RID"})
                break

    n_participants = df["RID"].nunique() if "RID" in df.columns else "unknown"
    logger.info(
        "ADNIMERGE standardized: %d rows, %s participants", len(df), n_participants
    )
    return df


def load_somascan_adni(config: dict) -> pd.DataFrame:
    """Load all ADNI SomaScan CSV files and concatenate.

    Reads all CSV files from the SomaScan directory, concatenates them,
    parses RID and VISCODE from the SampleId column, and retains only
    RID, VISCODE, PlateId, and seq.* columns.

    Parameters
    ----------
    config : dict
        Configuration dictionary with paths.adni_somascan_dir.

    Returns
    -------
    pd.DataFrame
        Concatenated SomaScan DataFrame.
    """
    somascan_dir = Path(config["paths"]["adni_somascan_dir"])

    if not somascan_dir.exists():
        raise FileNotFoundError(
            f"ADNI SomaScan directory not found at {somascan_dir}. "
            "Download SomaScan data from adni.loni.usc.edu."
        )

    csv_files = sorted(somascan_dir.glob("*.csv"))
    if not csv_files:
        raise FileNotFoundError(
            f"No CSV files found in {somascan_dir}. "
            "Download SomaScan data from adni.loni.usc.edu."
        )

    dfs = []
    for f in csv_files:
        logger.info("Reading SomaScan file: %s", f.name)
        df = pd.read_csv(f, low_memory=False)
        dfs.append(df)

    df = pd.concat(dfs, ignore_index=True)
    logger.info(
        "Concatenated %d SomaScan files: %d total rows", len(csv_files), len(df)
    )

    # Standardize column names — seq columns use dots
    df.columns = df.columns.str.replace("-", ".")

    # Rename R-exported SomaScan columns: X10000.28 -> seq.10000.28 (Rule 2)
    # R prefixes numeric/dot column names with X when writing to CSV.
    rename_map = {
        c: "seq." + c[1:]
        for c in df.columns
        if re.match(r"^X\d+\.\d+$", c)
    }
    if rename_map:
        df = df.rename(columns=rename_map)
        logger.info(
            "Renamed %d R-format SomaScan columns (X#.# -> seq.#.#)",
            len(rename_map),
        )

    # Parse RID and VISCODE from SampleId
    # Try multiple known patterns for ADNI SampleId formats
    sample_id_col = None
    for candidate in ["SampleId", "SAMPLEID", "Sample_ID", "SampleID"]:
        if candidate in df.columns:
            sample_id_col = candidate
            break

    if sample_id_col:
        # Pattern 1: "RID_VISCODE" (e.g., "1234_bl", "1234_m06")
        # Pattern 2: "ADNI_RID_VISCODE" (e.g., "ADNI_1234_bl")
        # Pattern 3: numeric RID already in a separate column
        parsed = df[sample_id_col].astype(str).str.extract(
            r"(?:ADNI_)?(\d+)_([a-zA-Z0-9]+)$"
        )

        if parsed.notna().all(axis=1).any():
            df["RID"] = pd.to_numeric(parsed[0], errors="coerce")
            df["VISCODE"] = parsed[1].str.lower()
            n_parsed = df["RID"].notna().sum()
            n_failed = df["RID"].isna().sum()
            if n_failed > 0:
                logger.warning(
                    "SampleId parsing: %d succeeded, %d failed", n_parsed, n_failed
                )
        else:
            logger.warning(
                "SampleId parsing failed for all rows. Check the SampleId format "
                "in the downloaded files and update the regex."
            )

    # If RID/VISCODE already exist as separate columns, use them
    if "RID" not in df.columns:
        for candidate in ["SubjectID", "SUBJECT_ID", "Subject_ID"]:
            if candidate in df.columns:
                df["RID"] = pd.to_numeric(df[candidate], errors="coerce")
                break

    if "VISCODE" not in df.columns:
        for candidate in ["Visit", "VISIT", "VisitCode"]:
            if candidate in df.columns:
                df["VISCODE"] = df[candidate].astype(str).str.lower()
                break

    # Identify protein columns
    seq_cols = identify_seq_columns(df)

    # Identify PlateId column
    plate_col = None
    for candidate in ["PlateId", "PLATEID", "Plate_ID", "PlateRunDate"]:
        if candidate in df.columns:
            plate_col = candidate
            break

    # Keep only essential columns + protein columns
    keep_cols = ["RID", "VISCODE"]
    if plate_col:
        df = df.rename(columns={plate_col: "PlateId"})
        keep_cols.append("PlateId")
    keep_cols.extend(seq_cols)

    df = df[[c for c in keep_cols if c in df.columns]]

    logger.info(
        "SomaScan loaded: %d samples, %d proteins, %d participants",
        len(df),
        len(seq_cols),
        df["RID"].nunique() if "RID" in df.columns else 0,
    )
    return df


def load_plasma_biomarkers_adni(config: dict) -> pd.DataFrame:
    """Load ADNI plasma biomarker files and merge.

    Reads available biomarker CSVs (p-tau181, p-tau217, NfL, GFAP,
    Abeta42, Abeta40), merges on RID + VISCODE, and computes
    the Abeta42/Abeta40 ratio.

    Parameters
    ----------
    config : dict
        Configuration dictionary with paths.adni_biomarkers_dir.

    Returns
    -------
    pd.DataFrame or None
        Merged biomarker DataFrame, or None if no files found.
    """
    biomarker_dir = Path(config["paths"]["adni_biomarkers_dir"])

    if not biomarker_dir.exists():
        logger.warning("ADNI biomarkers directory not found at %s", biomarker_dir)
        return None

    csv_files = sorted(biomarker_dir.glob("*.csv"))
    if not csv_files:
        logger.warning("No biomarker CSV files found in %s", biomarker_dir)
        return None

    merged = None
    for f in csv_files:
        logger.info("Reading biomarker file: %s", f.name)
        df = pd.read_csv(f, low_memory=False)
        df.columns = df.columns.str.upper()

        # Standardize participant ID
        if "RID" not in df.columns:
            for candidate in ["PTID", "SUBJECT_ID"]:
                if candidate in df.columns:
                    df = df.rename(columns={candidate: "RID"})
                    break

        if "RID" not in df.columns or "VISCODE" not in df.columns:
            logger.warning(
                "Biomarker file %s missing RID or VISCODE, skipping", f.name
            )
            continue

        if merged is None:
            merged = df
        else:
            merge_cols = ["RID", "VISCODE"]
            # Avoid duplicating columns
            new_cols = [
                c for c in df.columns if c not in merged.columns or c in merge_cols
            ]
            merged = merged.merge(df[new_cols], on=merge_cols, how="outer")

    if merged is None:
        return None

    # Compute Abeta42/Abeta40 ratio if both are present
    abeta42_col = None
    abeta40_col = None
    for col in merged.columns:
        if "ABETA42" in col.upper() or "AB42" in col.upper():
            abeta42_col = col
        if "ABETA40" in col.upper() or "AB40" in col.upper():
            abeta40_col = col

    if abeta42_col and abeta40_col:
        merged["ABETA42_40_RATIO"] = (
            pd.to_numeric(merged[abeta42_col], errors="coerce")
            / pd.to_numeric(merged[abeta40_col], errors="coerce")
        )
        logger.info("Computed Abeta42/Abeta40 ratio")

    logger.info(
        "Biomarkers loaded: %d rows, %d columns, %d participants",
        len(merged),
        len(merged.columns),
        merged["RID"].nunique(),
    )
    return merged


def assign_conversion_labels(
    adnimerge: pd.DataFrame, config: dict
) -> pd.DataFrame:
    """Assign trajectory labels and months-to-conversion for each participant.

    Iterates over each participant's diagnosis trajectory and assigns:
    - MCI_to_Dementia: any MCI visit followed by Dementia at a later visit
    - stable_MCI: MCI throughout with sufficient follow-up
    - CN_amyloid_negative: cognitively normal, amyloid negative
    - CN_amyloid_positive: cognitively normal, amyloid positive
    - other: all remaining (excluded from primary analysis)

    For converters, computes MONTHS_TO_CONVERSION as months from each visit
    to the first Dementia diagnosis.

    Parameters
    ----------
    adnimerge : pd.DataFrame
        Standardized ADNIMERGE DataFrame with DX, EXAMDATE, RID columns.
    config : dict
        Configuration with adni.stable_followup_min_months.

    Returns
    -------
    pd.DataFrame
        DataFrame with TRAJECTORY and MONTHS_TO_CONVERSION columns added.
    """
    adni_cfg = config["adni"]
    min_followup = adni_cfg["stable_followup_min_months"]

    df = adnimerge.copy()
    df["TRAJECTORY"] = "other"
    df["MONTHS_TO_CONVERSION"] = np.nan

    if "DX" not in df.columns:
        logger.warning("DX column not found — cannot assign conversion labels")
        return df

    # Standardize DX values
    dx_map = {}
    for val in df["DX"].dropna().unique():
        val_lower = str(val).lower().strip()
        if "dementia" in val_lower or val_lower == "ad":
            dx_map[val] = "Dementia"
        elif "mci" in val_lower or "lmci" in val_lower or "emci" in val_lower:
            dx_map[val] = "MCI"
        elif "cn" in val_lower or "nl" in val_lower or "normal" in val_lower:
            dx_map[val] = "CN"
        else:
            dx_map[val] = str(val)

    df["DX_STD"] = df["DX"].map(dx_map)

    trajectory_counts = {}

    for rid, group in df.groupby("RID"):
        group = group.sort_values("EXAMDATE")
        idx = group.index
        dx_sequence = group["DX_STD"].values
        dates = group["EXAMDATE"].values

        # Check for MCI -> Dementia conversion
        has_mci = "MCI" in dx_sequence
        has_dementia = "Dementia" in dx_sequence

        if has_mci and has_dementia:
            # Find first Dementia visit
            dementia_indices = group[group["DX_STD"] == "Dementia"].index
            first_dementia_idx = dementia_indices[0]
            first_dementia_date = group.loc[first_dementia_idx, "EXAMDATE"]

            # Check that MCI occurred before Dementia
            mci_before = group[
                (group["DX_STD"] == "MCI")
                & (group["EXAMDATE"] < first_dementia_date)
            ]

            if len(mci_before) > 0:
                df.loc[idx, "TRAJECTORY"] = "MCI_to_Dementia"

                # Compute months to conversion for each visit
                for i in idx:
                    visit_date = df.loc[i, "EXAMDATE"]
                    if pd.notna(visit_date) and pd.notna(first_dementia_date):
                        delta = (first_dementia_date - visit_date).days
                        df.loc[i, "MONTHS_TO_CONVERSION"] = delta / 30.44

                trajectory_counts["MCI_to_Dementia"] = (
                    trajectory_counts.get("MCI_to_Dementia", 0) + 1
                )
                continue

        # Stable MCI: all visits are MCI with sufficient follow-up
        if has_mci and not has_dementia:
            valid_dates = group["EXAMDATE"].dropna()
            if len(valid_dates) >= 2:
                followup_months = (
                    (valid_dates.max() - valid_dates.min()).days / 30.44
                )
                if followup_months >= min_followup:
                    df.loc[idx, "TRAJECTORY"] = "stable_MCI"
                    trajectory_counts["stable_MCI"] = (
                        trajectory_counts.get("stable_MCI", 0) + 1
                    )
                    continue

        # CN groups by amyloid status
        all_cn = all(dx == "CN" for dx in dx_sequence if pd.notna(dx))
        if all_cn and len(dx_sequence) > 0:
            # Check amyloid status
            amyloid_col = None
            for candidate in ["AMYLOID_STATUS", "AV45_STATUS", "AMYLOID"]:
                if candidate in group.columns:
                    amyloid_col = candidate
                    break

            if amyloid_col and group[amyloid_col].notna().any():
                # Use the most recent non-null amyloid status
                amyloid_val = group[amyloid_col].dropna().iloc[-1]
                if amyloid_val in [1, True, "positive", "Positive", "1"]:
                    df.loc[idx, "TRAJECTORY"] = "CN_amyloid_positive"
                    trajectory_counts["CN_amyloid_positive"] = (
                        trajectory_counts.get("CN_amyloid_positive", 0) + 1
                    )
                else:
                    df.loc[idx, "TRAJECTORY"] = "CN_amyloid_negative"
                    trajectory_counts["CN_amyloid_negative"] = (
                        trajectory_counts.get("CN_amyloid_negative", 0) + 1
                    )
            else:
                # No amyloid data — classify as CN without subtype
                df.loc[idx, "TRAJECTORY"] = "CN_amyloid_negative"
                trajectory_counts["CN_amyloid_negative"] = (
                    trajectory_counts.get("CN_amyloid_negative", 0) + 1
                )
            continue

        trajectory_counts["other"] = trajectory_counts.get("other", 0) + 1

    # Clean up
    df = df.drop(columns=["DX_STD"], errors="ignore")

    logger.info("Trajectory label assignment:")
    for traj, count in sorted(trajectory_counts.items()):
        logger.info("  %s: %d participants", traj, count)

    return df


def merge_adni_data(
    adnimerge: pd.DataFrame,
    somascan: pd.DataFrame,
    biomarkers: pd.DataFrame | None = None,
) -> pd.DataFrame:
    """Merge ADNI clinical, proteomics, and biomarker data.

    Inner join of clinical + proteomics on RID + VISCODE (only visits
    where both exist). Left join of biomarkers if provided.

    Parameters
    ----------
    adnimerge : pd.DataFrame
        Clinical data from load_adnimerge + assign_conversion_labels.
    somascan : pd.DataFrame
        Proteomics data from load_somascan_adni.
    biomarkers : pd.DataFrame or None
        Biomarker data from load_plasma_biomarkers_adni.

    Returns
    -------
    pd.DataFrame
        Merged DataFrame.
    """
    logger.info(
        "Merging: ADNIMERGE (%d rows) + SomaScan (%d rows)",
        len(adnimerge),
        len(somascan),
    )

    # Inner join clinical + proteomics
    merged = adnimerge.merge(somascan, on=["RID", "VISCODE"], how="inner")
    logger.info("After clinical-proteomics inner join: %d rows", len(merged))

    # Left join biomarkers
    if biomarkers is not None:
        pre_merge = len(merged)
        merged = merged.merge(biomarkers, on=["RID", "VISCODE"], how="left")
        logger.info(
            "After biomarker left join: %d rows (was %d)", len(merged), pre_merge
        )

    n_participants = merged["RID"].nunique()
    n_visits = len(merged)
    logger.info(
        "Final merged ADNI dataset: %d visits from %d participants",
        n_visits,
        n_participants,
    )
    return merged
